config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :pedidos

  resources :items

  resources :categoria

  resources :usuarios

  resources :produtos

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	has_many :items
	belongs_to :usuario
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @produtos = Produto.all
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido criado com sucesso.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params[:pedido]
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_for(@pedido) do |f| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% @pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td></td>   
      <td>Produtos</td>
      <td>Quantidade</td>
      <td>Preço</td>
    </tr>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= check_box("post", "validated")%></td>
        <td><%= link_to "#{produto.nome}", produto %></td>
        <td><%= text_field(:quantidade, :title, size: 10) %></td>
        <td><%= "#{produto.preco}" %></td>
      </tr>
    <% end %>

  </tbody>
</table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<h1>Listing pedidos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= link_to 'Show', pedido %></td>
        <td><%= link_to 'Edit', edit_pedido_path(pedido) %></td>
        <td><%= link_to 'Destroy', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>Faça o seu pedido!</h1>

<%= render 'form' %>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>